name: Build Gallery App

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # Allows you to run this manually button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build Debug APK
      # We added --no-daemon to prevent the memory crash
      run: ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: My-Smart-Gallery
        path: app/build/outputs/apk/debug/app-debug.apk
